// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	GetMostPopularResourceTypeSectionTimeframeRequest
	CatResult
	CatsResponse
	MostPopularResponse
	MostPopularResult
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetMostPopularResourceTypeSectionTimeframeRequest struct {
	// mostemailed|mostviewed|mostshared
	ResourceType string `protobuf:"bytes,1,opt,name=ResourceType" json:"ResourceType,omitempty"`
	// ie. Style, Arts, Books, Opinion
	Section string `protobuf:"bytes,2,opt,name=Section" json:"Section,omitempty"`
	// days to include. 1, 7 or 30
	Timeframe int32 `protobuf:"varint,3,opt,name=Timeframe" json:"Timeframe,omitempty"`
}

func (m *GetMostPopularResourceTypeSectionTimeframeRequest) Reset() {
	*m = GetMostPopularResourceTypeSectionTimeframeRequest{}
}
func (m *GetMostPopularResourceTypeSectionTimeframeRequest) String() string {
	return proto.CompactTextString(m)
}
func (*GetMostPopularResourceTypeSectionTimeframeRequest) ProtoMessage() {}
func (*GetMostPopularResourceTypeSectionTimeframeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0}
}

func (m *GetMostPopularResourceTypeSectionTimeframeRequest) GetResourceType() string {
	if m != nil {
		return m.ResourceType
	}
	return ""
}

func (m *GetMostPopularResourceTypeSectionTimeframeRequest) GetSection() string {
	if m != nil {
		return m.Section
	}
	return ""
}

func (m *GetMostPopularResourceTypeSectionTimeframeRequest) GetTimeframe() int32 {
	if m != nil {
		return m.Timeframe
	}
	return 0
}

type CatResult struct {
	Body   string `protobuf:"bytes,4,opt,name=Body" json:"Body,omitempty"`
	Byline string `protobuf:"bytes,3,opt,name=Byline" json:"Byline,omitempty"`
	Title  string `protobuf:"bytes,2,opt,name=Title" json:"Title,omitempty"`
	URL    string `protobuf:"bytes,1,opt,name=URL" json:"URL,omitempty"`
}

func (m *CatResult) Reset()                    { *m = CatResult{} }
func (m *CatResult) String() string            { return proto.CompactTextString(m) }
func (*CatResult) ProtoMessage()               {}
func (*CatResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CatResult) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *CatResult) GetByline() string {
	if m != nil {
		return m.Byline
	}
	return ""
}

func (m *CatResult) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CatResult) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

type CatsResponse struct {
	NumResults uint32       `protobuf:"varint,2,opt,name=NumResults" json:"NumResults,omitempty"`
	Results    []*CatResult `protobuf:"bytes,3,rep,name=Results" json:"Results,omitempty"`
	Status     string       `protobuf:"bytes,1,opt,name=Status" json:"Status,omitempty"`
}

func (m *CatsResponse) Reset()                    { *m = CatsResponse{} }
func (m *CatsResponse) String() string            { return proto.CompactTextString(m) }
func (*CatsResponse) ProtoMessage()               {}
func (*CatsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CatsResponse) GetNumResults() uint32 {
	if m != nil {
		return m.NumResults
	}
	return 0
}

func (m *CatsResponse) GetResults() []*CatResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *CatsResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type MostPopularResponse struct {
	NumResults uint32               `protobuf:"varint,2,opt,name=NumResults" json:"NumResults,omitempty"`
	Results    []*MostPopularResult `protobuf:"bytes,3,rep,name=Results" json:"Results,omitempty"`
	Status     string               `protobuf:"bytes,1,opt,name=Status" json:"Status,omitempty"`
}

func (m *MostPopularResponse) Reset()                    { *m = MostPopularResponse{} }
func (m *MostPopularResponse) String() string            { return proto.CompactTextString(m) }
func (*MostPopularResponse) ProtoMessage()               {}
func (*MostPopularResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MostPopularResponse) GetNumResults() uint32 {
	if m != nil {
		return m.NumResults
	}
	return 0
}

func (m *MostPopularResponse) GetResults() []*MostPopularResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *MostPopularResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type MostPopularResult struct {
	Abstract      string `protobuf:"bytes,10,opt,name=Abstract" json:"Abstract,omitempty"`
	AssetID       uint64 `protobuf:"varint,3,opt,name=AssetID" json:"AssetID,omitempty"`
	Byline        string `protobuf:"bytes,7,opt,name=Byline" json:"Byline,omitempty"`
	Column        string `protobuf:"bytes,5,opt,name=Column" json:"Column,omitempty"`
	ID            uint64 `protobuf:"varint,2,opt,name=ID" json:"ID,omitempty"`
	Keywords      string `protobuf:"bytes,4,opt,name=Keywords" json:"Keywords,omitempty"`
	PublishedDate string `protobuf:"bytes,11,opt,name=PublishedDate" json:"PublishedDate,omitempty"`
	Section       string `protobuf:"bytes,6,opt,name=Section" json:"Section,omitempty"`
	Source        string `protobuf:"bytes,12,opt,name=Source" json:"Source,omitempty"`
	Title         string `protobuf:"bytes,9,opt,name=Title" json:"Title,omitempty"`
	Type          string `protobuf:"bytes,8,opt,name=Type" json:"Type,omitempty"`
	URL           string `protobuf:"bytes,1,opt,name=URL" json:"URL,omitempty"`
}

func (m *MostPopularResult) Reset()                    { *m = MostPopularResult{} }
func (m *MostPopularResult) String() string            { return proto.CompactTextString(m) }
func (*MostPopularResult) ProtoMessage()               {}
func (*MostPopularResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MostPopularResult) GetAbstract() string {
	if m != nil {
		return m.Abstract
	}
	return ""
}

func (m *MostPopularResult) GetAssetID() uint64 {
	if m != nil {
		return m.AssetID
	}
	return 0
}

func (m *MostPopularResult) GetByline() string {
	if m != nil {
		return m.Byline
	}
	return ""
}

func (m *MostPopularResult) GetColumn() string {
	if m != nil {
		return m.Column
	}
	return ""
}

func (m *MostPopularResult) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *MostPopularResult) GetKeywords() string {
	if m != nil {
		return m.Keywords
	}
	return ""
}

func (m *MostPopularResult) GetPublishedDate() string {
	if m != nil {
		return m.PublishedDate
	}
	return ""
}

func (m *MostPopularResult) GetSection() string {
	if m != nil {
		return m.Section
	}
	return ""
}

func (m *MostPopularResult) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *MostPopularResult) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *MostPopularResult) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *MostPopularResult) GetURL() string {
	if m != nil {
		return m.URL
	}
	return ""
}

func init() {
	proto.RegisterType((*GetMostPopularResourceTypeSectionTimeframeRequest)(nil), "api.GetMostPopularResourceTypeSectionTimeframeRequest")
	proto.RegisterType((*CatResult)(nil), "api.CatResult")
	proto.RegisterType((*CatsResponse)(nil), "api.CatsResponse")
	proto.RegisterType((*MostPopularResponse)(nil), "api.MostPopularResponse")
	proto.RegisterType((*MostPopularResult)(nil), "api.MostPopularResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ApiService service

type ApiServiceClient interface {
	// Request recent articles about cats.
	GetCats(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*CatsResponse, error)
	// Request the most popular articles.
	GetMostPopularResourceTypeSectionTimeframe(ctx context.Context, in *GetMostPopularResourceTypeSectionTimeframeRequest, opts ...grpc.CallOption) (*MostPopularResponse, error)
}

type apiServiceClient struct {
	cc *grpc.ClientConn
}

func NewApiServiceClient(cc *grpc.ClientConn) ApiServiceClient {
	return &apiServiceClient{cc}
}

func (c *apiServiceClient) GetCats(ctx context.Context, in *google_protobuf.Empty, opts ...grpc.CallOption) (*CatsResponse, error) {
	out := new(CatsResponse)
	err := grpc.Invoke(ctx, "/api.ApiService/GetCats", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apiServiceClient) GetMostPopularResourceTypeSectionTimeframe(ctx context.Context, in *GetMostPopularResourceTypeSectionTimeframeRequest, opts ...grpc.CallOption) (*MostPopularResponse, error) {
	out := new(MostPopularResponse)
	err := grpc.Invoke(ctx, "/api.ApiService/GetMostPopularResourceTypeSectionTimeframe", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ApiService service

type ApiServiceServer interface {
	// Request recent articles about cats.
	GetCats(context.Context, *google_protobuf.Empty) (*CatsResponse, error)
	// Request the most popular articles.
	GetMostPopularResourceTypeSectionTimeframe(context.Context, *GetMostPopularResourceTypeSectionTimeframeRequest) (*MostPopularResponse, error)
}

func RegisterApiServiceServer(s *grpc.Server, srv ApiServiceServer) {
	s.RegisterService(&_ApiService_serviceDesc, srv)
}

func _ApiService_GetCats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetCats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ApiService/GetCats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetCats(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApiService_GetMostPopularResourceTypeSectionTimeframe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMostPopularResourceTypeSectionTimeframeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApiServiceServer).GetMostPopularResourceTypeSectionTimeframe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.ApiService/GetMostPopularResourceTypeSectionTimeframe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApiServiceServer).GetMostPopularResourceTypeSectionTimeframe(ctx, req.(*GetMostPopularResourceTypeSectionTimeframeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApiService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.ApiService",
	HandlerType: (*ApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCats",
			Handler:    _ApiService_GetCats_Handler,
		},
		{
			MethodName: "GetMostPopularResourceTypeSectionTimeframe",
			Handler:    _ApiService_GetMostPopularResourceTypeSectionTimeframe_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 493 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0x71, 0xec, 0x24, 0xf5, 0x34, 0xa9, 0xe8, 0x80, 0xa2, 0x55, 0x40, 0x28, 0xb2, 0x38,
	0x44, 0x1c, 0x5c, 0x28, 0x52, 0xef, 0x69, 0x82, 0xaa, 0x88, 0x0f, 0x55, 0x9b, 0x70, 0x46, 0x4e,
	0x32, 0x2d, 0x96, 0xec, 0xac, 0xf1, 0xae, 0x41, 0x3e, 0xc1, 0x1b, 0xf0, 0x3c, 0x3c, 0x01, 0xaf,
	0x85, 0xbc, 0x5e, 0xbb, 0x36, 0xe5, 0x10, 0x6e, 0xfb, 0x9f, 0x9d, 0xaf, 0x9d, 0xfd, 0x0d, 0x0c,
	0x25, 0xa5, 0x5f, 0xc3, 0x2d, 0xf9, 0x49, 0x2a, 0x94, 0x40, 0x3b, 0x48, 0xc2, 0xf1, 0x93, 0x5b,
	0x21, 0x6e, 0x23, 0x3a, 0xd3, 0xa6, 0x4d, 0x76, 0x73, 0x46, 0x71, 0xa2, 0xf2, 0xd2, 0xc3, 0xfb,
	0x69, 0xc1, 0xab, 0x2b, 0x52, 0xef, 0x85, 0x54, 0xd7, 0x22, 0xc9, 0xa2, 0x20, 0xe5, 0x24, 0x45,
	0x96, 0x6e, 0x69, 0x9d, 0x27, 0xb4, 0xa2, 0xad, 0x0a, 0xc5, 0x7e, 0x1d, 0xc6, 0x74, 0x93, 0x06,
	0x31, 0x71, 0xfa, 0x92, 0x91, 0x54, 0xe8, 0xc1, 0xa0, 0xe9, 0xc6, 0xac, 0x89, 0x35, 0x75, 0x79,
	0xcb, 0x86, 0x0c, 0xfa, 0x26, 0x9c, 0x75, 0xf4, 0x75, 0x25, 0xf1, 0x29, 0xb8, 0x75, 0x46, 0x66,
	0x4f, 0xac, 0x69, 0x97, 0xdf, 0x19, 0xbc, 0x4f, 0xe0, 0xce, 0x03, 0xc5, 0x49, 0x66, 0x91, 0x42,
	0x04, 0xe7, 0x52, 0xec, 0x72, 0xe6, 0xe8, 0x0c, 0xfa, 0x8c, 0x23, 0xe8, 0x5d, 0xe6, 0x51, 0xb8,
	0x2f, 0x63, 0x5d, 0x6e, 0x14, 0x3e, 0x86, 0xee, 0x3a, 0x54, 0x11, 0x99, 0x72, 0xa5, 0xc0, 0x87,
	0x60, 0x7f, 0xe4, 0xef, 0x4c, 0x87, 0xc5, 0xd1, 0x4b, 0x60, 0x30, 0x0f, 0x94, 0xe4, 0x24, 0x13,
	0xb1, 0x97, 0x84, 0xcf, 0x00, 0x3e, 0x64, 0x71, 0x59, 0x50, 0xea, 0xe0, 0x21, 0x6f, 0x58, 0x70,
	0x0a, 0xfd, 0xea, 0xd2, 0x9e, 0xd8, 0xd3, 0xe3, 0xf3, 0x13, 0x3f, 0x48, 0x42, 0xbf, 0x6e, 0x92,
	0x57, 0xd7, 0x45, 0x67, 0x2b, 0x15, 0xa8, 0x4c, 0x9a, 0x72, 0x46, 0x79, 0xdf, 0xe1, 0x51, 0x7b,
	0xc0, 0x87, 0x15, 0x7e, 0xf9, 0x77, 0xe1, 0x91, 0x2e, 0xdc, 0x4e, 0x75, 0x50, 0x03, 0xbf, 0x3a,
	0x70, 0x7a, 0x2f, 0x0c, 0xc7, 0x70, 0x34, 0xdb, 0x48, 0x95, 0x06, 0x5b, 0xc5, 0x40, 0xfb, 0xd7,
	0xba, 0xf8, 0xbd, 0x99, 0x94, 0xa4, 0x96, 0x0b, 0x3d, 0x65, 0x87, 0x57, 0xb2, 0x31, 0xfe, 0x7e,
	0x6b, 0xfc, 0x23, 0xe8, 0xcd, 0x45, 0x94, 0xc5, 0x7b, 0xd6, 0x2d, 0xed, 0xa5, 0xc2, 0x13, 0xe8,
	0x2c, 0x17, 0xfa, 0x75, 0x0e, 0xef, 0x2c, 0x17, 0x45, 0xd5, 0xb7, 0x94, 0x7f, 0x13, 0xe9, 0x4e,
	0x9a, 0x6f, 0xad, 0x35, 0x3e, 0x87, 0xe1, 0x75, 0xb6, 0x89, 0x42, 0xf9, 0x99, 0x76, 0x8b, 0x40,
	0x11, 0x3b, 0xd6, 0x0e, 0x6d, 0x63, 0x93, 0xac, 0x5e, 0x9b, 0xac, 0xe2, 0xfd, 0x9a, 0x40, 0x36,
	0x30, 0xef, 0xd7, 0xea, 0x0e, 0x0d, 0xb7, 0x89, 0x06, 0x82, 0xa3, 0xe9, 0x3d, 0x2a, 0xe1, 0xd2,
	0xd4, 0xde, 0xc3, 0xe5, 0xfc, 0xb7, 0x05, 0x30, 0x4b, 0xc2, 0x55, 0xb9, 0x58, 0x78, 0x01, 0xfd,
	0x2b, 0x52, 0x05, 0x40, 0x38, 0xf2, 0xcb, 0xcd, 0xf2, 0xab, 0xcd, 0xf2, 0xdf, 0x14, 0x9b, 0x35,
	0x3e, 0xad, 0xf8, 0xa8, 0x19, 0xf3, 0x1e, 0xe0, 0x0f, 0x0b, 0x5e, 0x1c, 0xbe, 0x68, 0x78, 0xa1,
	0x73, 0xfc, 0xf7, 0x66, 0x8e, 0xd9, 0x3f, 0x10, 0x31, 0x2d, 0x6c, 0x7a, 0xba, 0xcf, 0xd7, 0x7f,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xfe, 0xc6, 0x74, 0x7c, 0x25, 0x04, 0x00, 0x00,
}
