// Code generated by protoc-gen-go.
// source: mostpopular.proto
// DO NOT EDIT!

/*
Package nyt is a generated protocol buffer package.

It is generated from these files:
	mostpopular.proto

It has these top-level messages:
	MostPopularResponse
	MostPopularResult
	Media
	MediaMetadata
*/
package nyt

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type MostPopularResponse struct {
	Status     string               `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Copyright  string               `protobuf:"bytes,2,opt,name=copyright" json:"copyright,omitempty"`
	NumResults uint32               `protobuf:"varint,3,opt,name=num_results" json:"num_results,omitempty"`
	Results    []*MostPopularResult `protobuf:"bytes,4,rep,name=results" json:"results,omitempty"`
}

func (m *MostPopularResponse) Reset()         { *m = MostPopularResponse{} }
func (m *MostPopularResponse) String() string { return proto.CompactTextString(m) }
func (*MostPopularResponse) ProtoMessage()    {}

func (m *MostPopularResponse) GetResults() []*MostPopularResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type MostPopularResult struct {
	Url           string   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Id            uint64   `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	AsssetId      uint64   `protobuf:"varint,3,opt,name=assset_id" json:"assset_id,omitempty"`
	AdxKeywords   string   `protobuf:"bytes,4,opt,name=adx_keywords" json:"adx_keywords,omitempty"`
	Column        string   `protobuf:"bytes,5,opt,name=column" json:"column,omitempty"`
	Section       string   `protobuf:"bytes,6,opt,name=section" json:"section,omitempty"`
	Byline        string   `protobuf:"bytes,7,opt,name=byline" json:"byline,omitempty"`
	Type          string   `protobuf:"bytes,8,opt,name=type" json:"type,omitempty"`
	Title         string   `protobuf:"bytes,9,opt,name=title" json:"title,omitempty"`
	Abstract      string   `protobuf:"bytes,10,opt,name=abstract" json:"abstract,omitempty"`
	PublishedDate string   `protobuf:"bytes,11,opt,name=published_date" json:"published_date,omitempty"`
	Source        string   `protobuf:"bytes,12,opt,name=source" json:"source,omitempty"`
	Views         uint32   `protobuf:"varint,13,opt,name=views" json:"views,omitempty"`
	Media         []*Media `protobuf:"bytes,14,rep,name=media" json:"media,omitempty"`
}

func (m *MostPopularResult) Reset()         { *m = MostPopularResult{} }
func (m *MostPopularResult) String() string { return proto.CompactTextString(m) }
func (*MostPopularResult) ProtoMessage()    {}

func (m *MostPopularResult) GetMedia() []*Media {
	if m != nil {
		return m.Media
	}
	return nil
}

type Media struct {
	Type          string           `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Subtype       string           `protobuf:"bytes,2,opt,name=subtype" json:"subtype,omitempty"`
	Caption       string           `protobuf:"bytes,3,opt,name=caption" json:"caption,omitempty"`
	Copyright     string           `protobuf:"bytes,4,opt,name=copyright" json:"copyright,omitempty"`
	MediaMetadata []*MediaMetadata `protobuf:"bytes,5,rep,name=media_metadata" json:"media-metadata,omitempty"`
}

func (m *Media) Reset()         { *m = Media{} }
func (m *Media) String() string { return proto.CompactTextString(m) }
func (*Media) ProtoMessage()    {}

func (m *Media) GetMediaMetadata() []*MediaMetadata {
	if m != nil {
		return m.MediaMetadata
	}
	return nil
}

type MediaMetadata struct {
	Url    string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Format string `protobuf:"bytes,2,opt,name=format" json:"format,omitempty"`
	Height uint32 `protobuf:"varint,3,opt,name=height" json:"height,omitempty"`
	Width  uint32 `protobuf:"varint,4,opt,name=width" json:"width,omitempty"`
}

func (m *MediaMetadata) Reset()         { *m = MediaMetadata{} }
func (m *MediaMetadata) String() string { return proto.CompactTextString(m) }
func (*MediaMetadata) ProtoMessage()    {}

func init() {
}
