package pubsub

// Code generated by protoc-gen-go.
// source: session_message.proto
// DO NOT EDIT!

/*
Package regi is a generated protocol buffer package.

It is generated from these files:
	session_message.proto

It has these top-level messages:
	SessionMessage
*/

import proto "github.com/golang/protobuf/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

// SessionMessage is used for encrypting messages in our pubsub queues.
type SessionMessage struct {
	// *
	// Encrypted using the RSA public key corresponding to the decalred version
	EncryptedMaterial []byte   `protobuf:"bytes,1,opt,name=encrypted_material,proto3" json:"encrypted_material,omitempty"`
	EncryptedMessages [][]byte `protobuf:"bytes,2,rep,name=encrypted_messages,proto3" json:"encrypted_messages,omitempty"`
}

func (m *SessionMessage) Reset()         { *m = SessionMessage{} }
func (m *SessionMessage) String() string { return proto.CompactTextString(m) }
func (*SessionMessage) ProtoMessage()    {}

func init() {
}
